### ISSUE TITLE
ERR_INVALID_RESPONSE from getallattempts.php

### ISSUE THREAD

**Issue by fstonedahl** [trampgeek/moodle-qtype_coderunner#115] opened 2021-03-13 18:17 UTC
Following the documentation at https://github.com/trampgeek/moodle-qtype_coderunner#administrator-scripts

I can successfully go to:

MOODLEHOME/question/type/coderunner/downloadquizattempts.php 

where I see a list of Moodle courses that I have access to, and a list of quizzes for each course.  However, when I click to download the data for a *specific quiz* (in any format), then that takes me to:

MOODLEHOME/question/type/coderunner/getallattempts.php?quizid=1234&format=excel

BUT, instead of downloading the data file with all of the student quiz attempt data, I get this error:

"This site can’t be reached.  The webpage at MOODLEHOME/question/type/coderunner/getallattempts.php?quizid=1234&format=excel might be temporarily down or it may have moved permanently to a new web address.
**ERR_INVALID_RESPONSE**"

Now, I believe this feature was working correctly last Spring when our college was self-hosting our Moodle server last year, but then last summer we a) switched to Moodle hosting provider (eThink education), and b) upgraded to a new version of Moodle (3.9.1, I think), and I suspect this broke the feature.

My hunch is that this would be caused by some configuration issue on the Moodle server / web server...  Any idea what might cause this, so I can provide suggestions to the support folks at eThink to get it resolved?  (Or, any idea for further debugging steps to determine the source of the error?)

**Comment by trampgeek** [comment] 2021-03-13 21:25
I don't have any immediate explanation for that. I assume from what you're saying that the problem occurs with all quizzes in all formats?

Without direct access to the server to check the logs, this could be hard to diagnose. The only thing I can suggest is that you use the network tab in the developer tools (SHIFT-CTRL-I) to track what happens when you attempt to access the data. Specifically what's the status code returned and how quickly is it returned?

From what I'm seeing on a quick Google, this message can be browser dependent - have you tried with any other browsers?

**Comment by fstonedahl** [comment] 2021-03-14 21:57
It appears to be returning a 404 code.  This seems strange to me, because when I navigate directly to: MOODLEHOME/question/type/coderunner/getallattempts.php
(without passing the GET parameters), it gives me back a slightly friendlier Moodle error page saying "A required parameter (quizid) was missing".  

So I think getallattempts.php is not missing from the server, BUT when trying to fetch the data for any quiz from any course, it sends back a 404.  

Is it expected behavior for this script to send back a 404 code if the quizID is not found, or in some other situation?

**Comment by trampgeek** [comment] 2021-03-14 23:24
This is strange. The "missing parameter" response proves that _getallattempts.php_ is present and running OK. So it looks like there's an error occurring when getallattempts.php runs and that error is somehow being passed back (erroneously) as a 404. Certainly there's nothing in my code that directly sets a 404. In fact, there's not much code in getallattempts.php - see [here](https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/getallattempts.php). It's mostly just a large complex DB query that gets passed to standard Moodle code to export a table of results.

An SQL error is the most likely point of failure in there, though I've not idea why that should result in a 404. Nor do I see why you'd get a DB error, anyway. Unless your new system is using a different DB from the normal mysql or mariadb and my query doesn't work with that new database?

Without the ability to replicate the problem myself or even see the Apache error log, I'm rather stumped myself, sorry.

**Comment by jtsafran** [comment] 2021-04-08 15:52
Hi all!  I work at eThink.  The issue is that this site runs on Postgres, which is a supported Moodle database, along with MySQL/MariaDB, SQL Server, and Oracle https://docs.moodle.org/dev/Moodle_architecture#Overview_of_a_Moodle_installation

Can the code be updated to support Postgres?  It should look something like:

`SELECT concat(quiza.uniqueid, qasd.attemptstepid, qasd.id) as uniquekey,
        quiza.uniqueid as quizattemptid,
        timestart,
        timefinish,
        u.firstname,
        u.lastname,
        u.email,
        qatt.slot,
        qatt.questionid,
        qatt.questionsummary,
        quest.name as qname,
        slot.maxmark as mark,
        qattsteps.timecreated as timestamp,
        to_timestamp(qattsteps.timecreated) as datetime,
        qattsteps.fraction,
        qattsteps.state,
        qasd.attemptstepid,
        qasd.name as qasdname,
        qasd.value as value FROM mdl_user u
    JOIN mdl_quiz_attempts quiza ON quiza.userid = u.id AND quiza.quiz = 369
    JOIN mdl_question_attempts qatt ON qatt.questionusageid = quiza.uniqueid
    JOIN mdl_question_attempt_steps qattsteps ON qattsteps.questionattemptid = qatt.id
    JOIN mdl_question_attempt_step_data qasd on qasd.attemptstepid = qattsteps.id
    JOIN mdl_question quest ON quest.id = qatt.questionid
    JOIN mdl_quiz_slots slot ON qatt.slot = slot.slot AND slot.quizid = quiza.quiz WHERE quiza.preview = 0
    AND (qasd.name NOT SIMILAR TO '^-_' OR qasd.name = '-_rawfraction')
    AND (qasd.name NOT SIMILAR TO '^_' OR qasd.name = '_testoutcome')
    AND quest.length > 0
    ORDER BY quiza.uniqueid, timestamp LIMIT 1`

**Comment by trampgeek** [comment] 2021-08-28 01:44
Sorry about the silence on this one. It went into the too-hard bin. I've just been looking at it again and it still seems too hard, sorry. The getallattempts.php script is a minor add-on to CodeRunner and as far as I know very few people use it. The FROM_UNIXTIME  function is supported by myql/MariaDB and Oracle. Postgres has to_timetamp which is supported by Oracle as well but not by mysql/MariaDB. AFAIK there's no DB-independent solution here and I think the current code supports the vast majority of users. So I'm going to close this now, but if you have a DB-independent solution please re-open.

**Closed by trampgeek** 2021-08-28 01:44 UTC
