### ISSUE TITLE
Minor issue with % in penaltyregime

### ISSUE THREAD

**Issue by timhunt** [trampgeek/moodle-qtype_coderunner#96] opened 2020-05-06 11:16 UTC
Judging by the validation code, a penaltyregime like 2%, 4%, ... should work fine.

However, on our server, for a question like that, we get a PHP notice like:

Notice: A non well formed numeric value encountered in /srv/moodle.open.ac.uk/www/html/question/behaviour/adaptive_adapted_for_coderunner/behaviour.php on line 191

I don't think this is a serious problem, but I thought I would report it.

This may be something that changes in a recent PHP version. We are on PHP 7.3.16.

**Comment by trampgeek** [comment] 2020-07-19 09:20
Sorry about the delay in getting to look at this, Tim.
Thanks for reporting, but I can't reproduce the problem. I've tried on a server with PHP 7.4.3 and another with PHP 7.2.24. Both servers had maximum error reporting on, and there were no notices in the Apache error log and nothin on screen. I used exactly the penalty regime you gave above.

I'm going to put it down to a temporary weirdness in PHP 7.3 and close the issue. Please reopen if you can help me pin down the problem better.

**Closed by trampgeek** 2020-07-19 09:20 UTC
